### ISSUE TITLE
Usage with different AION releases

### ISSUE THREAD

**Issue by ToJen** [satran004/aion-graphql#4]
Hey Satya, this project is interesting and very useful. Would it be possible to create a Gitter channel to discuss the project. Myself and @arjitkhullar will be exploring this for future projects. Is this library built to work with any AION version or is this a specific version?

**Comment by satran004** [comment]
Hi @ToJen, Thanks for your interest in the project. As suggested here is link to the Gitter channel https://gitter.im/aion-graphql/Lobby  .
> Is this library built to work with any AION version or is this a specific version?
Currently it's supporting the latest version of AION mainnet. Through Java API v0.1.14. The compatibility depends on the particular AION java api version which I believe will be backward compatible.

**Comment by ToJen** [comment]
Thanks!
